version: '3'
services:
  db-service:
    image: neo4j:latest
    networks: [temp]
    ports: 
      - 7474:7474
      - 7687:7687
    environment:
      - NEO4J_dbms_security_procedures_unrestricted=apoc.*
      - NEO4J_apoc_import_file_enabled=true
      - NEO4J_dbms_shell_enabled=true
      - NEO4J_dbms_connector_bolt_listen_address=0.0.0.0
      - NEO4J_AUTH=neo4j/secret
  app-service:
        image: tempservice:latest
        depends_on: [db-service]
        ports:
            - 8080:8080
        networks: [temp]
networks:
  temp: